[package]
name = "ryanlua/purse"
description = "CoreGui decoupled version of the Roblox default backpack"
version = "1.1.2"
license = "Apache-2.0"
authors = ["Ryan Luu <ryan.luu@ryanluu.dev>"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
homepage = "http://purse.luau.page/"
repository = "https://github.com/ryanlua/purse"
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json", "LICENSE", "README.md"]

[dependencies]
topbarplus = "1foreverhd/topbarplus@3.4.0"
