name: CI

on:
  pull_request:
    paths:
      - ".github/workflows/ci.yml"
      - "**.luau"
  push:
    paths:
      - ".github/workflows/ci.yml"
      - "**.luau"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Run StyLua
        run: stylua --check src/ models/

      - name: Run selene
        run: selene src/ models/
